#!/bin/sh
# Stamps a fresh version onto every JS module URL in index.html so browsers
# never mix cached old modules with new ones (GitHub Pages caches for 10 min).
# Rewrites the block between the modules:start / modules:end markers.
set -e
cd "$(dirname "$0")/.."
V=$(date +%Y%m%d%H%M%S)
{
  echo '<!-- modules:start (generated by scripts/stamp-version.sh) -->'
  echo '<script type="importmap">'
  echo '{ "imports": {'
  first=1
  for f in js/*.js js/viz/*.js; do
    [ "$first" = 1 ] && first=0 || printf ',\n'
    printf '  "./%s": "./%s?v=%s"' "$f" "$f" "$V"
  done
  printf '\n} }\n'
  echo '</script>'
  echo "<script type=\"module\" src=\"js/main.js?v=$V\"></script>"
  echo '<!-- modules:end -->'
} > /tmp/stamp-block.html
python3 - "$V" <<'PY'
import re, sys
s = open('index.html').read()
block = open('/tmp/stamp-block.html').read().rstrip('\n')
s2 = re.sub(r'<!-- modules:start.*?<!-- modules:end -->', lambda m: block, s, flags=re.S)
s2 = re.sub(r'href="styles\.css(\?v=\d+)?"', 'href="styles.css?v=' + sys.argv[1] + '"', s2)
assert s2 != s or block in s, 'markers not found'
open('index.html', 'w').write(s2)
PY
echo "stamped modules v=$V"
